## 1: Scraping using Pandas libraries

In [1]:
import pandas as pd
import requests
from io import StringIO  # ← Yeh add karo

url = "https://en.wikipedia.org/wiki/Demographics_of_Pakistan"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# Step 1: HTML fetch karo
response = requests.get(url, headers=headers)

# Step 2: StringIO mein wrap karo ← Yahi fix hai
tables = pd.read_html(StringIO(response.text))

# Step 3: Tables check karo
print(f"Number of tables found: {len(tables)}")

# Step 4: Pehli table dekho
tables[4].head()  # ← Yeh change karo, 23 se pehle check karo ki kitni tables hain

Number of tables found: 34

,Province or Territory,1951[14],1961[14],1972[14],1981[14],1998[14],2017[9],2023[16]
0,Punjab,20540762,25463974,37607423,47292441,73691290,109989655,127688922.0
1,Sindh,6047748,8367065,14155909,19028666,30439893,47854510,55696147.0
2,Khyber Pakhtunkhwa,5888550,7578186,10879781,13259875,20919976,35501964,40856097.0
3,Balochistan,1167167,1353484,2428678,4332376,6565885,12335129,14894402.0
4,ICT,—,117669,237549,340286,805235,2003368,2363863.0

In [8]:
import pandas as pd

url = "https://www.worldometers.info/world-population/population-by-country/"

# Fetch the HTML content
import requests

# header to avoid blocking by the website
headers = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}

response = requests.get(url, headers=headers)
response.raise_for_status()

from io import StringIO
tables = pd.read_html(StringIO(response.text))
print(f"Number of tables found: {len(tables)}")

tables[0].head()  # First table is usually the one we want

# # sAVE THE DATA TO CSV
# tables[0].to_csv("population_by_country_2-6-2026.csv", index=False)

Number of tables found: 1

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,1476625576,0.87%,12760051,497,2973190,"â440,456",1.93,29.2,37.6%,17.79%
1,2,China,1412914089,â0.22%,"â3,182,005",150,9388211,"â232,107",1.03,40.6,68.7%,17.02%
2,3,United States,349035494,0.51%,1759687,38,9147420,1177848,1.63,38.7,83.1%,4.20%
3,4,Indonesia,287886782,0.76%,2165546,159,1811570,"â39,472",2.08,30.7,60.3%,3.47%
4,5,Pakistan,259299791,1.6%,4080237,336,770880,"â1,144,738",3.44,20.8,34.7%,3.12%